SAFECDX-1730/complete profile handling web and mobile
opencdx/opencdx-gui pull request #94
Opened 2024-11-04 11:24 UTC by kriti-safehealth

2024-11-04 17:56 UTC, karthick-safe requested changes

2024-11-04 17:56 UTC, karthick-safe commented on opencdx-form-render/components/ui/DateOfBirthPicker.tsx
> +import DateTimePicker, { DateType } from 'react-native-ui-datepicker';
Please try using https://docs.expo.dev/versions/latest/sdk/date-time-picker/

2024-11-05 14:36 UTC, karthick-safe approved these changes

2024-11-06 14:07 UTC, pChou19 approved these changes

2024-11-06 14:08 UTC, merged